---
# API Reference: http://manageiq.org/docs/reference/latest/api/reference/custom_attributes
- name: Add Custom Attribute to VM or Instance
  hosts: localhost
  connection: local
  gather_facts: false
  #user: root
  #vars:
  tasks:
  - name: CloudForms | Lookup instance href
    uri:
      url: "{{ manageiq.api_url }}/api/vms?filter[]=name={{ item }}&expand=resources"
      method: GET
      body:
        action: refresh
      body_format: json
      validate_certs: False
      headers:
        X-Auth-Token: "{{ manageiq.api_token }}"
        Content-Type: "application/json"
      status_code: 200
    register: instance_output
    with_items: 
      - "finaltest"
  
  - debug: var=instance_output

  - name: fail when VM not found in VMDB
    fail:
      msg: "Cannot find VM in VMDB."
    when: "item.json.resources[0].id is undefined"
    with_items: "{{ instance_output.results }}"

  - name: Assign Custom Attribute
    uri:
      url: "{{ manageiq.api_url }}/api/vms/{{ item.json.resources[0].id }}/custom_attributes"
      method: POST
      body_format: json
      body:
        action: add
        resources: 
          - name: "ca1"
            value: "value 1"
          - name: "ca2"
            value: "value 2"
      validate_certs: False
      headers:
        X-Auth-Token: "{{ manageiq.api_token }}"
        Content-Type: "application/json"
      status_code: 200
    with_items: "{{ instance_output.results }}"
    register: output

  - debug: var=output

  - name: Get Custom Attributes for VM 
    uri:
      url: "{{ manageiq.api_url }}/api/vms/{{ item.json.resources[0].id }}/custom_attributes"
      method: GET
      validate_certs: False
      headers:
        X-Auth-Token: "{{ manageiq.api_token }}"
        Content-Type: "application/json"
      status_code: 200
    with_items: "{{ instance_output.results }}"
    register: custom_attributes
 
  - debug: var=custom_attributes

  - name: Fail if custom attributes don't exist
    fail: msg="{{item}} not in custom attributes"
    when: "'{{item}}' not in custom_attributes.stdout"
    with_items: 
      - ca1
      - ca2


