---
- name: Copy public RHEL AMI to private
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    instance_type: t2.micro
    new_image_name: "rhel7.3"
    new_image_description: "Red Hat Enterprise Linux 7.3 (HVM), SSD Volume Type"
    #keypair: mykey
    security_group: default
    region: us-east-1
    vpc_subnet: subnet-8c0e27b0
    amis:
      us-east-1: "ami-b63769a1"
      us-east-2: "ami-0932686c"
      us-west-1: "ami-2cade64c"
      us-west-2: "ami-6f68cf0f"
      eu-west-1: "ami-02ace471"
      eu-central-1: "ami-e4c63e8b"
      ap-northeast-1: "ami-5de0433c"
      ap-northeast-2: "ami-44db152a"
      ap-southeast-1: "ami-2c95344f"
      ap-southeast-2: "ami-39ac915a"
      sa-east-1: "ami-7de77b11"
      ap-south-1: "ami-cdbdd7a2"
  tasks:
  - name: Create EC2 Instance from public AMI
    ec2:
      #key_name: "{{ keypair }}"
      group: "{{ security_group }}"
      region: "{{ region }}"
      instance_type: "{{ instance_type }}"
      image: "{{ amis[region] }}"
      wait: true
      wait_timeout: 500
      count: 1
      vpc_subnet_id: "{{ vpc_subnet }}"
      assign_public_ip: yes
    register: ec2

  #- name: Pause for 1 minute to let EC2 instance start 
  #    pause:
  #    minutes: 1

  ### SKIPPING wait_for as we may not have ssh access (and don't need it)
  #- name: Wait for SSH to come up
  #  wait_for:
  #    host: "{{ item.public_dns_name }}"
  #    port: 22
  #    delay: 60
  #    timeout: 320
  #    state: started
  #  with_items: "{{ ec2.instances }}"

  - name: Add instances to a group
    add_host:
      name: "{{ item.public_ip }}"
      groups: launched
    with_items: "{{ ec2.instances }}"

  #- debug: var=ec2

  - name: Create AMI from instance
    ec2_ami:
      region: "{{ region }}"
      instance_id: "{{ ec2.instances[0].id }}"
      wait: yes
      name: "{{ new_image_name }}"
      description: "{{ new_image_description }}"
    register: image

  - name: Terminate EC2 Instance
    ec2:
      state: "absent"
      region: "{{ region }}"
      instance_ids: "{{ ec2.instance_ids }}"
