---
- name: Provision EC2 Instances
  hosts: localhost
  connection: local
  gather_facts: false
  #user: root
  vars:
    instance_type: t2.micro
    image: ami-b63769a1
    keypair: mykey
    security_group: default
    region: us-east-1
    instance_count: 1
    monitoring: no
    vpc_subnet: default
  tasks:
  #- name: Find VCP Subnet for the cluster
  #  ec2_vpc_subnet_facts:
  #    region: "{{ region }}"
  #    filters:
  #      "tag:Name": "{{ vpc_subnet }}"
  #  register: vpc_subnet

  - name: Create EC2 Instances
    ec2:
      key_name: "{{ keypair }}"
      group: "{{ security_group }}"
      region: "{{ region }}"
      instance_type: "{{ bastion_instance_type }}"
      image: "{{ amis[region] }}"
      wait: true
      wait_timeout: 500
      count: "{{ instance_count }}"
      vpc_subnet_id: "{{ vpc_subnet }}"
      assign_public_ip: yes 
      monitoring: "{{ monitoring }}"


