---
### Simple test for setting a service name on provision
- name: Set service name
  hosts: localhost
  connection: local
  gather_facts: false
  #user: root
  vars:
    service_name: ""
    service_description: ""
    max_retries: 9
    retry_interval: 20
  tasks:
  - name: CloudForms | Set the Service URL
    set_fact:
      svc_url: "/api/{{ manageiq.service }}"

  - debug: var=svc_url

  - name: CloudForms | Get Service
    uri:
      url: "{{ manageiq.api_url }}{{ svc_url }}"
      method: GET
      body:
        action: refresh
      body_format: json
      validate_certs: False
      headers:
        X-Auth-Token: "{{ manageiq.api_token }}"
        Content-Type: "application/json" 
      status_code: 200
    register: service

  - debug: var=service

  - name: CloudForms | Update Service Name
    uri:
      url: "{{ manageiq.api_url }}{{ svc_url }}"
      method: POST
      body_format: json
      body:
        action: edit
        resource: 
          name: "{{ service_name }}"
          description:  "{{ service_description }}"
      validate_certs: False
      headers:
        X-Auth-Token: "{{ manageiq.api_token }}"
        Content-Type: "application/json"
      status_code: 200
    register: output
    when: "service_name is not null"

  - debug: var=output   
    when: "service_name is not null"



